Basics of numpy

In [2]:
import numpy as np


In [ ]:
# we created an 1D array
array = np.array([1, 2, 3, 4])
print("Array : ", array)

Array :  [1 2 3 4]


In [6]:
# creating an array of size 2 x 3 with all zeroes in it
array2_3 = np.zeros((2, 3))
print("The 2 x 3 array : \n", array2_3)

The 2 x 3 array : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# similarly with 1s
ones_array = np.ones((2, 3))
print("The ones array : \n", ones_array)


The ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#  Generating an array from 0 to 9 with a step of 2
range_array = np.arange(0, 10, 2)
print("Range array: ", range_array)

Range array:  [0 2 4 6 8]


In [ ]:
#  Generating 5 evenly spaced values between 0 and 2
linspace_array = np.linspace(0, 2, 5)
print("Linspace array: ", linspace_array)

Linspace array:  [0.  0.5 1.  1.5 2. ]


In [13]:
# Reshaping a 1D array into 2D array
original_array = np.array([1, 2, 3, 4])
reshaped_array = original_array.reshape(2, 2)
print("Original array : ", original_array)
print("Reshaped array :\n", reshaped_array)


Original array :  [1 2 3 4]
Reshaped array :
 [[1 2]
 [3 4]]


In [14]:
# Calculating the statistics of an array
data = np.array([1, 2, 3, 4, 5, 6])
# mean
mean_data = np.mean(data)
print("Mean value: ", mean_data)

# median
median_data = np.median(data)
print("Median data: ", median_data)

std_dev_data = np.std(data)
print("Standard deviation: ", std_dev_data)




Mean value:  3.5
Median data:  3.5
Standard deviation:  1.707825127659933


In [16]:
# Normal arithmetics of an array
A = np.array([6, 4, 2, 4, 1, 3])

# sum
sum_A = np.sum(A)
print("Sum : ", sum_A)

# max
max_A = np.max(A)
print("Max : ", max_A)

# min
min_A = np.min(A)
print("Min : ", min_A)

# sort
sorted_A = np.sort(A)
print("Sorted Array : ", sorted_A)



Sum :  20
Max :  6
Min :  1
Sorted Array :  [1 2 3 4 4 6]


In [17]:
# generating random number of size 2 x 2
rand_A = np.random.rand(2, 2)
print("Random Array:\n", rand_A)


Random Array:
 [[0.35472342 0.19462547]
 [0.88302795 0.01536602]]


In [18]:
# Solving a linear equation AX = B
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
solution = np.linalg.solve(A, B)
print("Solution: ", solution)


Solution:  [2. 3.]


In [20]:
#File operations

# Saving a file
array = np.array([1, 2 , 3, 4, 5, 6])
np.save('array.npy', array)
print("Array saved to array.npy")

#Loading an array from file
loaded_array = np.load('array.npy')
print("Loaded Array:", loaded_array) 

Array saved to array.npy
Loaded Array: [1 2 3 4 5 6]
