GOING THROUGH NUMPY QUESTIONS IN gfg

In [1]:
import numpy as np

How to create an empty and a full NumPy array?

In [ ]:
np_empty = np.empty((2,3))
print(np_empty) # random garbage value

np_full = np.full((2, 3), 5)
print(np_full)

[[0. 0. 0.]
 [0. 0. 0.]]
[[5 5 5]
 [5 5 5]]


Create a Numpy array filled with all zeros

In [11]:
np_zeros = np.zeros((2, 3), dtype = int)
print(np_zeros)

[[0 0 0]
 [0 0 0]]


Create array filled with all ones

In [ ]:
np_ones = np.ones(3) # have same syntax as np.zeros()
print(np_ones)

[1. 1. 1.]


Check whether a Numpy array contains a specified row

In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]) 
  
# view array 
print(arr) 
  
# check for some lists 
print([1, 2, 3, 4, 5] in arr.tolist()) 
print([16, 17, 20, 19, 18] in arr.tolist()) 
print([3, 2, 5, -4, 5] in arr.tolist()) 
print([11, 12, 13, 14, 15] in arr.tolist()) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


How to Remove rows in Numpy array that contains non-numeric values?

In [15]:
# Creating a 2x3 2-D NumPy array
n_arr = np.array([[10.5, 22.5, 3.8], [41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all rows containing NaN values:")
cleaned_arr = n_arr[~np.isnan(n_arr).any(axis=1)]
print(cleaned_arr)

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing NaN values:
[[10.5 22.5  3.8]]


Breakdown of above code
Step-by-Step Breakdown
1. np.isnan(n_arr)
This returns a boolean mask of the same shape as n_arr, where each element is True if it's NaN and False otherwise.
2. .any(axis=1)
This checks each row (axis=1) to see if it contains any True (NaN values).
It returns a 1D boolean array, where True means the row has at least one NaN.
3. ~ (Bitwise NOT)
The ~ operator inverts the boolean values:
True → False
False → True
This means rows with NaN become False, and rows without NaN become True.
4. n_arr[...] (Indexing)
This selects only the rows where the condition is True, i.e., rows that don’t contain NaN.

Find the most frequent value in a NumPy array
idea:
    Create a NumPy array.
    Apply bincount() method of NumPy to get the count of occurrences of each element in the array.
    The n, apply argmax() method to get the value having a maximum number of occurrences(frequency).

In [16]:
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print("Original array:") 
print(x) 
  
print("Most frequent value in the above array:") 
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


How to compare two NumPy arrays?

In [17]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])
 
print("Array a: ", a)
print("Array b: ", b)
 
print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))

Array a:  [101  99  87]
Array b:  [897  97 111]
a > b
[False  True False]
a >= b
[False  True False]
a < b
[ True False  True]
a <= b
[ True False  True]


np.moveaxis() is used to reorder the axes of an array. It does not modify the data but simply changes how the axes are indexed.

Syntax: np.moveaxis(array, source, destination)
array: The input NumPy array.
source: The index of the axis you want to move.
destination: The index where you want to place that axis.


In [18]:
arr = np.zeros((2, 3, 4))  # Shape (2, 3, 4)

# Swap axis 1 (second) and axis 2 (third)
swapped_arr = np.moveaxis(arr, 1, 2)
print(swapped_arr.shape)  # Output: (2, 4, 3)

arr = np.ones((2, 3, 4))  # Shape (2, 3, 4)

# Move last axis (-1) to the first position (0)
new_arr = np.moveaxis(arr, -1, 0)
print(new_arr.shape)  # Output: (4, 2, 3)

(2, 4, 3)
(4, 2, 3)


Numpy count_nonzero method

In [19]:
arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7]] 
  
gfg = np.count_nonzero(arr) 
  
print (gfg)  

6


List Slicing

1D ARRAY

In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:6])    # [2 3 4 5]
print(arr[:5])     # [0 1 2 3 4]
print(arr[4:])     # [4 5 6 7 8 9]
print(arr[::2])    # [0 2 4 6 8] (Every 2nd element)
print(arr[::-1])   # [9 8 7 6 5 4 3 2 1 0] (Reverse)


[2 3 4 5]
[0 1 2 3 4]
[4 5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


2D array

In [21]:
matrix = np.array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11]])

print(matrix[1:, 2:])  # Extract rows 1 onwards & columns 2 onwards
# [[ 6  7]
#  [10 11]]

print(matrix[:, 1])    # Second column: [1 5 9]

print(matrix[0:2, 1:3])  # Extract sub-matrix from row 0-1, column 1-2
# [[1 2]
#  [5 6]]
print(matrix[-2:, -2:])  # Last 2 rows, last 2 columns
# [[ 6  7]
#  [10 11]]
print(matrix[:, ::2])  # Every alternate column
# [[ 0  2]
#  [ 4  6]
#  [ 8 10]]
arr[2:5] = [100, 101, 102]  
print(arr)  # [0 1 100 101 102 5 6 7 8 9]
# Remove the second row (index 1)
new_matrix = np.delete(matrix, 1, axis=0)

# Remove the third column (index 2)
new_matrix = np.delete(matrix, 2, axis=1)


[[ 6  7]
 [10 11]]
[1 5 9]
[[1 2]
 [5 6]]
[[ 6  7]
 [10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[  0   1 100 101 102   5   6   7   8   9]
