Matrices in numpy

In [11]:
import numpy as np

Creating Matrices

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Matrix Addition & Subtraction

In [13]:
print(A + B)  

print(A - B)  

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


Matrix Multiplication

In [14]:
print(A * B)  # Elemnet wise

print(A @ B)  # normal dot product type

print(np.dot(A, B))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Transpose of a Matrix

In [15]:
print(A.T)

[[1 3]
 [2 4]]


Determinant of a Matrix

In [16]:
print(np.linalg.det(A)) 

-2.0000000000000004


Inverse of a Matrix

In [17]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Solving a System of Linear Equations (Ax = B)

In [18]:
B = np.array([5, 11])
x = np.linalg.solve(A, B)
print(x) 

[1. 2.]
